name: project-events

on:
  project_v2_item:
    types: [created, edited, deleted]

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: "1.24"
      - name: send-notification
        env:
          ITEM_ID: ${{ github.event.projects_v2_item.node_id }}
          EVENT: ${{ github.event.action }}
          SENDER: ${{ github.event.sender.login }}
        run: |
          go run ./cmd/gpb notify \
            --github-token="${{ secrets.GITHUB_TOKEN }}" \
            --item-id="${ITEM_ID}" \
            --event="${EVENT}" \
            --sender="${SENDER}" \
            --bale-token="${{ secrets.BALE_TOKEN }}" \
            --chat-id="${{ vars.CHAT_ID }}"
